### ISSUE TITLE
Does the oidc client library need to be a singleton?

### ISSUE THREAD

**Issue by shuppert** [markphillips100/oidc-cordova-demo#1]
I'm working on integrating the oidc-client library into an existing Sencha Touch application.  I noticed that in your sample you wrapped the oidc library in an Angular service.  Did this solve any issues for you or is this just an easy way to integrate into an Angular application?

In my work so far I have multiple instances of UserManager in the places where they're used (login, logout, etc).  I'm considering wrapping the oidc library in a Sencha class and using it from multiple places as a singleton but I'm not sure if it's worth the effort.  I have login and logout working with the inAppBrowser but I'm running into sporadic issues (freezing on iOS and crashing on Android).  I'd appreciate any advice or recommendations you have on the best way to integrate the library.

**Comment by markphillips100** [comment]
The service's responsibility was simply to supply a globally accessible user login state, profile data and token that would change accordingly as the single UserManager fired its events.  It fires its own event to notify anything in the app interested in such information so that they can update their views.

I think the UserManager itself "may" get into issues if multiple instances were running, especially for silent renew as this would call for multiple InAppBrowser instances too.  I'm just not sure if this plays nicely or not.  I've never had such issues with the singleton approach so I'd recommend doing the same.

**Comment by shuppert** [comment]
Thanks Mark.  I appreciate the advice.  I'm going to pursue the singleton and hopefully that resolves my issues.

**Comment by brockallen** [comment]
The UserManager could be used as multiple instances, but generally is designed to have a single instance. You could use multiple, but then as @markphillips100 said, you'd want to configure only one to do certain tasks (such as silent renew).

**Comment by shuppert** [comment]
Thanks Brock.  I'm not using silent renew but it was cleaner to write a singleton wrapper around UserManager for me.  Our application uses the inAppBrowser in multiple places and I think I'm running into issues where the application is trying to use the inAppBrowser before CordovaPopupWindow destroys it's handle to it.  Have you seen anything like that?

**Comment by brockallen** [comment]
No, I've not seen anything like that.

**Comment by markphillips100** [comment]
I haven't experienced that either

**Comment by shuppert** [comment]
Thanks for your input.  I was able to get things working after moving things to a singleton class.  On to the next issue.  :)

**Comment by shuppert** [comment]
FYI- After more debugging and issues with the app freezing on iOS I found that there are issues with blocking calls in InAppBrowser and WKWebView.  This has been patched in a PR but hasn't been included in a release of InAppBrowser.  However, saphocom created a fork labeled as 1.4.2 which includes the fix.

Related links:
https://issues.apache.org/jira/browse/CB-11136
https://github.com/apache/cordova-plugin-inappbrowser/pull/162
https://github.com/saphocom/cordova-plugin-inappbrowser
