### ISSUE TITLE
connecting to IdentityProvider gets UNABLE_TO_VERIFY_LEAF_SIGNATURE error

### ISSUE THREAD

**Issue by myaesubi** [markphillips100/oidc-cordova-demo#2]
Hello Mark,

First off, thanks for the demo code you provided. 

I trying to connect to one of the IdentityServer3 samples; AspNetIdentity sample. 
I know this error is a certificate issue, though I have the certificate that comes with the AspNetIdentity sample installed and validated in Trusted Root Certificate store as well.

I can connect to the Identity Provider sample with other clients, like console app client with no issue.
However, when I try the Cordova app in Visual Studio with like 'Ripple' emulators, I get the 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' error on connection.

I wonder if I miss something here.

Appreciate your response.
Mohammad

**Comment by markphillips100** [comment]
The Cordova demo is dependent on the inappbrowser plugin and ripple
emulators don't load plugins as far as I know.

**Comment by myaesubi** [comment]
Thanks. I see the plugin in the project file select. 
So I'm just wondering how can I test the app? Is there specific target in Visual Studio I should choose to run the app or I need to deploy it to a device and test?

Thanks again,
Mohammad

**Comment by markphillips100** [comment]
It is possible to use vs emulator for Android against URLs on the same host
but I've found in the past to have issues with certs this way too. There's
no substitute for deploying to a real device on consuming dns resolvable
endpoints.

**Comment by myaesubi** [comment]
Thank you. I pursue the real device and dns resolvables on my azure app services.
